Base: 
  state_dim: &state_dim 2  
  length: 20000
  burn: 1000
  multi_proposal: False

Target:
  class: MultiPeaksTarget
  MultiPeaksTarget:
    seed: 21
    pos_range:
      - -5
      - 5
    var_range:
      - .1
      - 4
    state_dim: *state_dim 
    peaks_num: 4

Kernal:
  class: HMC_Kernal
  M_H_Kernal:
    state_dim: *state_dim
  MultiTry_M_H_Kernal:
    state_dim: *state_dim
    try_n: 4
  HMC_Kernal:
    state_dim: *state_dim
    epsilon: .1
    L: 5

ProposalKernal:
  class: LangevinKernal
  NormalKernal:
    sigma: 1
    state_dim: *state_dim
  LangevinKernal:
    delta: .1
    epsilon: .00001
    state_dim: *state_dim

MultiProposalKernal:
  Kernal_1:
    class: NormalKernal
    NormalKernal:
      sigma: 1
      state_dim: *state_dim
  Kernal_2:
    class: NormalKernal
    NormalKernal:
      sigma: 2
      state_dim: *state_dim
  Kernal_3:
    class: NormalKernal
    NormalKernal:
      sigma: .5
      state_dim: *state_dim
  Kernal_4:
    class: LangevinKernal
    LangevinKernal:
      delta: .1
      epsilon: .00001
      state_dim: *state_dim      

Chain:
  class: M_H_Chain
  M_H_Chain:
    
  PT_M_H_Chain:
    temperatures:
      - .9
      - .8
      - .6
      - .3
      - .1
      -  0