Base: 
  state_dim: &state_dim 2  
  length: 20000
  burn: 1000

Target:
  class: MultiPeaksTarget
  MultiPeaksTarget:
    seed: 21
    pos_range:
      - -5
      - 5
    var_range:
      - .1
      - 4
    state_dim: *state_dim 
    peaks_num: 4

  
Kernal:
  class: M_H_Kernal
  M_H_Kernal:
    state_dim: *state_dim

ProposalKernal:
  class: LangevinKernal
  NormalKernal:
    sigma: 1
    state_dim: *state_dim
  LangevinKernal:
    delta: 1
    epsilon: .00001
    state_dim: *state_dim

Chain:
  class: PT_M_H_Chain
  M_H_Chain:
    
  PT_M_H_Chain:
    temperatures:
      - .9
      - .8
      - .6
      - .3
      - .1
      -  0